[package]
name = "pong-0"
version = "0.1.0"
edition = "2021"
authors = ["James Miles jmstudyacc@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = "0.20.1"